# --- GDB & pyOCD Thread Awareness ---
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y

# --- Compiler & Assertions ---
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2

# --- Fault Isolation & Stack Safety ---
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_INIT_STACKS=y
CONFIG_STACK_SENTINEL=y

# --- Synchronous Logging ---
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y